version: "2"
services:
  redis:
    image: redis
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    ports:
      - "4000:3000"
    restart: always
    container_name: prep
    depends_on:
      - redis
