apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: prep
  labels:
    name: {name}-preproduction
  name: {name}-preproduction
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}-preproduction
    spec:
      containers:
      - name: redis
        image: redis
        ports:
         - containerPort: 6379
        resources:
         requests:
           memory: "0Mi"
           cpu: "0m"
      - name: {name}-preproduction
        image: vizzuality/{name}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: production
          - name: BASEMAP_TILE_URL
            value: http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png
          - name: WRI_API_URL
            value: https://api.resourcewatch.org/v1
          - name: BACKOFFICE_API_URL
            value: https://beta.prepdata.org/api
          - name: CONTROL_TOWER_URL
            value: https://production-api.globalforestwatch.org
          - name: CALLBACK_URL
            value: https://beta.prepdata.org/admin/auth
          - name: APPLICATIONS
            value: prep
          - name: SECRET
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: PREP_SECRET
        ports:
          - containerPort: 3000

      restartPolicy: Always
