apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: prep
  name: {name}-preproduction
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {name}-preproduction
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
